name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build & Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mern-backend ./backend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mern-backend

      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mern-frontend ./frontend  --build-arg REACT_APP_NODE_ENV='production'  --build-arg REACT_APP_URL='http://52.201.224.139:5000/'  
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mern-frontend

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Pull latest images from Docker Hub
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mern-backend
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mern-frontend
            
            # Stop & remove old containers if they exist
            docker stop mern-backend || true && docker rm mern-backend || true
            docker stop mern-frontend || true && docker rm mern-frontend || true
            
            # Run new containers
            docker run -d -p 5000:5000 --name mern-backend ${{ secrets.DOCKER_HUB_USERNAME }}/mern-backend
            docker run -d -p 3000:3000 --name mern-frontend ${{ secrets.DOCKER_HUB_USERNAME }}/mern-frontend
